CREATE TABLE balance
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount BIGINT                                  NOT NULL,
    CONSTRAINT pk_balance PRIMARY KEY (id),
    CONSTRAINT valid_amount CHECK (amount > 0)
);